In [19]:
import pandas as pd

# pre data processing #

In [20]:


# Load the datasets
fv_df = pd.read_excel("transaction_portion.xlsx")
nct_df = pd.read_excel("NCT Participants_2025_08_08.xlsx")

# Inspect to find the common key
print(fv_df.columns)
print(nct_df.columns)

Index(['PID', 'FULL_DATE', 'TRANSACTION_HEADER_KEY', 'STORE_NUMBER', 'AREA',
       'DEPARTMENT_NAME', 'CATEGORY_NAME', 'SECTION_NAME', 'SUB_SECTION_NAME',
       'PRIMARY_UPC', 'PRODUCT_DESCRIPTION', 'SIZE', 'UNIT_OF_MEASURE',
       'SALES', 'UNITS_WEIGHT', 'UNITS_PACKAGES', 'AD_TYPE_DESCRIPTION',
       'AVG_PRICE_PER_MEASURE', 'AVG_PRICE_PER_PACK', 'HUMAN_CONSUMABLE_CODE',
       'DIETITIAN_PICK', 'WIC_FLAG', 'FOOD_STAMP_FLAG', 'FV_DUMMY1',
       'FV_DUMMY2', 'UNIT_OF_MEASURE_mapped', 'FNDDS_SCHNUCKS',
       'standard_portion', 'transfer_g', 'final_weight', 'portion'],
      dtype='object')
Index(['PID', 'First & Last Name', 'Schnucks_Rewards', 'Intervention',
       'Phone #', 'Email', 'COHORT #', 'Start Date', 'End Date',
       'CUSTOMER_ID'],
      dtype='object')

In [21]:
nct_df=nct_df[['PID','Intervention','COHORT #', 'Start Date', 'End Date',
       'CUSTOMER_ID']]

In [22]:
fv_df

,PID,FULL_DATE,TRANSACTION_HEADER_KEY,STORE_NUMBER,AREA,DEPARTMENT_NAME,CATEGORY_NAME,SECTION_NAME,SUB_SECTION_NAME,PRIMARY_UPC,...,WIC_FLAG,FOOD_STAMP_FLAG,FV_DUMMY1,FV_DUMMY2,UNIT_OF_MEASURE_mapped,FNDDS_SCHNUCKS,standard_portion,transfer_g,final_weight,portion
0,101,2023-06-16,1360403179,301,Fresh,BAKERY,FRESH BAKERY,"FRESH DONUTS, DANISH & PASTRIES",FRESH MADE DONUTS,1307,...,N,Y,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,101,2023-06-16,1360403179,301,Center Store,DAIRY,MILK,"FLUID MILK-1/2 GAL., QTS., PNTS.",FLUID_MILK_SINGLE_SERVE,2800077212,...,N,Y,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300107,...,N,Y,1,3,NaN,NaN,120.0,28.35,28.00,6.615000
3,202,2025-02-05,1487627133,198,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,N,Y,1,3,NaN,NaN,120.0,28.35,14.00,3.307500
4,101,2023-06-18,1360874979,301,Fresh,BAKERY,FRESH BAKERY,"FRESH DONUTS, DANISH & PASTRIES",FRESH MADE DONUTS,1307,...,N,Y,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54057,340,2025-04-18,1502415078,143,Center Store,DRUGS,NUTRITION - DRUGS,ADULT NUTRITION,ADULT_NUTRI_PROTEIN,85002696950,...,N,Y,0,0,NaN,NaN,NaN,NaN,NaN,NaN
54058,320,2023-08-18,1373715278,266,Fresh,PRODUCE,COOKING VEG.,MISC. COOKING VEG.,MCV ZUCCHINI,4067,...,Y,Y,1,1,NaN,NaN,120.0,453.59,3.28,12.398127
54059,333,2023-09-04,1377219504,106,Fresh,PRODUCE,COOKING VEG.,MISC. COOKING VEG.,MCV ZUCCHINI,4067,...,Y,Y,1,1,NaN,NaN,120.0,453.59,0.57,2.154552
54060,340,2025-05-08,1506414496,107,Center Store,GROCERY,COMMERCIAL BAKERY - GROCERY,MAINSTREAM COMMERCIAL BREAD,WHITE & WHEAT BREAD,2412601868,...,N,Y,0,0,NaN,NaN,NaN,NaN,NaN,NaN
54061,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,Y,Y,1,1,g,200.0,120.0,1.00,600.00,5.000000

In [23]:
fv_df["PID"].nunique()

73

In [24]:
nct_df["PID"].nunique()

116

In [25]:
# Assuming the common key is 'PID' (adjust if needed)
merged_df = pd.merge(fv_df, nct_df, on='PID', how='left')

# Save the merged result
merged_df.to_excel("merged_fv_nct.xlsx", index=False)

In [26]:
merged_df

,PID,FULL_DATE,TRANSACTION_HEADER_KEY,STORE_NUMBER,AREA,DEPARTMENT_NAME,CATEGORY_NAME,SECTION_NAME,SUB_SECTION_NAME,PRIMARY_UPC,...,FNDDS_SCHNUCKS,standard_portion,transfer_g,final_weight,portion,Intervention,COHORT #,Start Date,End Date,CUSTOMER_ID
0,101,2023-06-16,1360403179,301,Fresh,BAKERY,FRESH BAKERY,"FRESH DONUTS, DANISH & PASTRIES",FRESH MADE DONUTS,1307,...,NaN,NaN,NaN,NaN,NaN,COUPON,1,2024-04-24,2024-10-09,311187789.0
1,101,2023-06-16,1360403179,301,Center Store,DAIRY,MILK,"FLUID MILK-1/2 GAL., QTS., PNTS.",FLUID_MILK_SINGLE_SERVE,2800077212,...,NaN,NaN,NaN,NaN,NaN,COUPON,1,2024-04-24,2024-10-09,311187789.0
2,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300107,...,NaN,120.0,28.35,28.00,6.615000,DELIVERY,9,2024-12-18,2025-06-04,149785823.0
3,202,2025-02-05,1487627133,198,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,NaN,120.0,28.35,14.00,3.307500,DELIVERY,1,2024-04-24,2024-10-09,159733124.0
4,101,2023-06-18,1360874979,301,Fresh,BAKERY,FRESH BAKERY,"FRESH DONUTS, DANISH & PASTRIES",FRESH MADE DONUTS,1307,...,NaN,NaN,NaN,NaN,NaN,COUPON,1,2024-04-24,2024-10-09,311187789.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54120,320,2023-08-18,1373715278,266,Fresh,PRODUCE,COOKING VEG.,MISC. COOKING VEG.,MCV ZUCCHINI,4067,...,NaN,120.0,453.59,3.28,12.398127,USUAL,6,2024-09-11,2025-02-26,357760797.0
54121,333,2023-09-04,1377219504,106,Fresh,PRODUCE,COOKING VEG.,MISC. COOKING VEG.,MCV ZUCCHINI,4067,...,NaN,120.0,453.59,0.57,2.154552,USUAL,9,2024-12-18,2025-06-04,449665128.0
54122,340,2025-05-08,1506414496,107,Center Store,GROCERY,COMMERCIAL BAKERY - GROCERY,MAINSTREAM COMMERCIAL BREAD,WHITE & WHEAT BREAD,2412601868,...,NaN,NaN,NaN,NaN,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0
54123,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,200.0,120.0,1.00,600.00,5.000000,DELIVERY,9,2024-12-18,2025-06-04,756859993.0
54124,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,200.0,120.0,1.00,600.00,5.000000,COUPON,9,2024-12-18,2025-06-04,717760798.0

In [27]:
merged_df.columns

Index(['PID', 'FULL_DATE', 'TRANSACTION_HEADER_KEY', 'STORE_NUMBER', 'AREA',
       'DEPARTMENT_NAME', 'CATEGORY_NAME', 'SECTION_NAME', 'SUB_SECTION_NAME',
       'PRIMARY_UPC', 'PRODUCT_DESCRIPTION', 'SIZE', 'UNIT_OF_MEASURE',
       'SALES', 'UNITS_WEIGHT', 'UNITS_PACKAGES', 'AD_TYPE_DESCRIPTION',
       'AVG_PRICE_PER_MEASURE', 'AVG_PRICE_PER_PACK', 'HUMAN_CONSUMABLE_CODE',
       'DIETITIAN_PICK', 'WIC_FLAG', 'FOOD_STAMP_FLAG', 'FV_DUMMY1',
       'FV_DUMMY2', 'UNIT_OF_MEASURE_mapped', 'FNDDS_SCHNUCKS',
       'standard_portion', 'transfer_g', 'final_weight', 'portion',
       'Intervention', 'COHORT #', 'Start Date', 'End Date', 'CUSTOMER_ID'],
      dtype='object')

In [28]:
merged_df["PID"].nunique()

73

In [29]:
# Allow FULL_DATE to be before Start Date (negative days are valid)
merged_df['days_since_start'] = (merged_df['FULL_DATE'] - merged_df['Start Date']).dt.days

# Bin into 2-week periods (each bin = 14 days), allowing negative bins
merged_df['week_bin'] = (merged_df['days_since_start'] // 14) * 2

# Keep only the 36 bins: from -26 to +50 (13 pre-trial, 13 in-trial, 13 post-trial)
data = merged_df[merged_df['week_bin'].between(-26, 50)]

# Label phase based on week_bin
def label_phase(x):
    if x <= -2:
        return 'Pre-Trial'
    elif 0 <= x <= 24:
        return 'In-Trial'
    elif x >= 26:
        return 'Post-Trial'
    else:
        return None  # week_bin == -0 or 23 are edge cases and excluded by design

merged_df['phase'] = merged_df['week_bin'].apply(label_phase)
data = merged_df[merged_df['week_bin'].between(-26, 50)]
merged_df

,PID,FULL_DATE,TRANSACTION_HEADER_KEY,STORE_NUMBER,AREA,DEPARTMENT_NAME,CATEGORY_NAME,SECTION_NAME,SUB_SECTION_NAME,PRIMARY_UPC,...,final_weight,portion,Intervention,COHORT #,Start Date,End Date,CUSTOMER_ID,days_since_start,week_bin,phase
0,101,2023-06-16,1360403179,301,Fresh,BAKERY,FRESH BAKERY,"FRESH DONUTS, DANISH & PASTRIES",FRESH MADE DONUTS,1307,...,NaN,NaN,COUPON,1,2024-04-24,2024-10-09,311187789.0,-313,-46,Pre-Trial
1,101,2023-06-16,1360403179,301,Center Store,DAIRY,MILK,"FLUID MILK-1/2 GAL., QTS., PNTS.",FLUID_MILK_SINGLE_SERVE,2800077212,...,NaN,NaN,COUPON,1,2024-04-24,2024-10-09,311187789.0,-313,-46,Pre-Trial
2,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300107,...,28.00,6.615000,DELIVERY,9,2024-12-18,2025-06-04,149785823.0,-58,-10,Pre-Trial
3,202,2025-02-05,1487627133,198,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,14.00,3.307500,DELIVERY,1,2024-04-24,2024-10-09,159733124.0,287,40,Post-Trial
4,101,2023-06-18,1360874979,301,Fresh,BAKERY,FRESH BAKERY,"FRESH DONUTS, DANISH & PASTRIES",FRESH MADE DONUTS,1307,...,NaN,NaN,COUPON,1,2024-04-24,2024-10-09,311187789.0,-311,-46,Pre-Trial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54120,320,2023-08-18,1373715278,266,Fresh,PRODUCE,COOKING VEG.,MISC. COOKING VEG.,MCV ZUCCHINI,4067,...,3.28,12.398127,USUAL,6,2024-09-11,2025-02-26,357760797.0,-390,-56,Pre-Trial
54121,333,2023-09-04,1377219504,106,Fresh,PRODUCE,COOKING VEG.,MISC. COOKING VEG.,MCV ZUCCHINI,4067,...,0.57,2.154552,USUAL,9,2024-12-18,2025-06-04,449665128.0,-471,-68,Pre-Trial
54122,340,2025-05-08,1506414496,107,Center Store,GROCERY,COMMERCIAL BAKERY - GROCERY,MAINSTREAM COMMERCIAL BREAD,WHITE & WHEAT BREAD,2412601868,...,NaN,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,29,4,In-Trial
54123,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,600.00,5.000000,DELIVERY,9,2024-12-18,2025-06-04,756859993.0,71,10,In-Trial
54124,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,600.00,5.000000,COUPON,9,2024-12-18,2025-06-04,717760798.0,71,10,In-Trial

In [30]:
# Find the dropped rows by comparing indexes
dropped_rows = merged_df[~merged_df.index.isin(data.index)]
dropped_rows
# Summarize unique PIDs and their associated Intervention and phase
drop_summary = dropped_rows.groupby(['PID','COHORT #', 'Intervention',])['phase'].first().reset_index()

drop_summary

    PID  COHORT # Intervention       phase
0   101         1       COUPON   Pre-Trial
1   102         1       COUPON   Pre-Trial
2   103         1       COUPON   Pre-Trial
3   104         1       COUPON  Post-Trial
4   105         2       COUPON   Pre-Trial
..  ...       ...          ...         ...
60  331         9        USUAL   Pre-Trial
61  333         9        USUAL   Pre-Trial
62  335        10        USUAL   Pre-Trial
63  336        10        USUAL   Pre-Trial
64  340        13        USUAL   Pre-Trial

[65 rows x 4 columns]

In [31]:
drop_summary.to_csv("drop_summary.csv", index=False)

In [32]:
data

,PID,FULL_DATE,TRANSACTION_HEADER_KEY,STORE_NUMBER,AREA,DEPARTMENT_NAME,CATEGORY_NAME,SECTION_NAME,SUB_SECTION_NAME,PRIMARY_UPC,...,final_weight,portion,Intervention,COHORT #,Start Date,End Date,CUSTOMER_ID,days_since_start,week_bin,phase
2,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300107,...,28.00,6.615000,DELIVERY,9,2024-12-18,2025-06-04,149785823.0,-58,-10,Pre-Trial
3,202,2025-02-05,1487627133,198,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,14.00,3.307500,DELIVERY,1,2024-04-24,2024-10-09,159733124.0,287,40,Post-Trial
9,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,14.00,3.307500,DELIVERY,9,2024-12-18,2025-06-04,149785823.0,-58,-10,Pre-Trial
18,121,2024-05-07,1429636284,227,Fresh,PRODUCE,FRESH FRUIT,PEARS,PEARS BULK,4025,...,2.53,9.563189,COUPON,6,2024-09-11,2025-02-26,477941158.0,-127,-20,Pre-Trial
19,131,2025-02-24,1491662710,196,Fresh,PRODUCE,FRESH FRUIT,PEARS,PEARS BULK,4025,...,1.70,6.425858,COUPON,8,2024-11-20,2025-05-07,831779326.0,96,12,In-Trial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54118,340,2025-04-18,1502415078,143,Center Store,DAIRY,SPREADS - DAIRY,BUTTER/SPREADS,SPREADS_BUTTER,4131854008,...,NaN,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,9,0,In-Trial
54119,340,2025-04-18,1502415078,143,Center Store,DRUGS,NUTRITION - DRUGS,ADULT NUTRITION,ADULT_NUTRI_PROTEIN,85002696950,...,NaN,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,9,0,In-Trial
54122,340,2025-05-08,1506414496,107,Center Store,GROCERY,COMMERCIAL BAKERY - GROCERY,MAINSTREAM COMMERCIAL BREAD,WHITE & WHEAT BREAD,2412601868,...,NaN,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,29,4,In-Trial
54123,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,600.00,5.000000,DELIVERY,9,2024-12-18,2025-06-04,756859993.0,71,10,In-Trial
54124,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,600.00,5.000000,COUPON,9,2024-12-18,2025-06-04,717760798.0,71,10,In-Trial

In [33]:
data['period_start'] = data['Start Date'] + pd.to_timedelta(data['week_bin'] * 7, unit='D')
data

/var/folders/rc/f8gf4g817rq5cl8_jh8vtny00000gn/T/ipykernel_1562/1695496176.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['period_start'] = data['Start Date'] + pd.to_timedelta(data['week_bin'] * 7, unit='D')

,PID,FULL_DATE,TRANSACTION_HEADER_KEY,STORE_NUMBER,AREA,DEPARTMENT_NAME,CATEGORY_NAME,SECTION_NAME,SUB_SECTION_NAME,PRIMARY_UPC,...,portion,Intervention,COHORT #,Start Date,End Date,CUSTOMER_ID,days_since_start,week_bin,phase,period_start
2,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300107,...,6.615000,DELIVERY,9,2024-12-18,2025-06-04,149785823.0,-58,-10,Pre-Trial,2024-10-09
3,202,2025-02-05,1487627133,198,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,3.307500,DELIVERY,1,2024-04-24,2024-10-09,159733124.0,287,40,Post-Trial,2025-01-29
9,233,2024-10-21,1465253192,227,Center Store,FROZEN FOOD,FROZEN VEGETABLES,VEGETABLES,VEGETABLES_BLENDS,3418300066,...,3.307500,DELIVERY,9,2024-12-18,2025-06-04,149785823.0,-58,-10,Pre-Trial,2024-10-09
18,121,2024-05-07,1429636284,227,Fresh,PRODUCE,FRESH FRUIT,PEARS,PEARS BULK,4025,...,9.563189,COUPON,6,2024-09-11,2025-02-26,477941158.0,-127,-20,Pre-Trial,2024-04-24
19,131,2025-02-24,1491662710,196,Fresh,PRODUCE,FRESH FRUIT,PEARS,PEARS BULK,4025,...,6.425858,COUPON,8,2024-11-20,2025-05-07,831779326.0,96,12,In-Trial,2025-02-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54118,340,2025-04-18,1502415078,143,Center Store,DAIRY,SPREADS - DAIRY,BUTTER/SPREADS,SPREADS_BUTTER,4131854008,...,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,9,0,In-Trial,2025-04-09
54119,340,2025-04-18,1502415078,143,Center Store,DRUGS,NUTRITION - DRUGS,ADULT NUTRITION,ADULT_NUTRI_PROTEIN,85002696950,...,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,9,0,In-Trial,2025-04-09
54122,340,2025-05-08,1506414496,107,Center Store,GROCERY,COMMERCIAL BAKERY - GROCERY,MAINSTREAM COMMERCIAL BREAD,WHITE & WHEAT BREAD,2412601868,...,NaN,USUAL,13,2025-04-09,2025-09-24,887413321.0,29,4,In-Trial,2025-05-07
54123,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,5.000000,DELIVERY,9,2024-12-18,2025-06-04,756859993.0,71,10,In-Trial,2025-02-26
54124,135,2025-02-27,1492145195,113,Fresh,PRODUCE,VALUE TRAY PACK PRODUCE,VALUE PRODUCE,VALU_VEG,4610301310,...,5.000000,COUPON,9,2024-12-18,2025-06-04,717760798.0,71,10,In-Trial,2025-02-26

In [34]:
data.to_excel("data.xlsx", index=False)

In [35]:
data.columns

Index(['PID', 'FULL_DATE', 'TRANSACTION_HEADER_KEY', 'STORE_NUMBER', 'AREA',
       'DEPARTMENT_NAME', 'CATEGORY_NAME', 'SECTION_NAME', 'SUB_SECTION_NAME',
       'PRIMARY_UPC', 'PRODUCT_DESCRIPTION', 'SIZE', 'UNIT_OF_MEASURE',
       'SALES', 'UNITS_WEIGHT', 'UNITS_PACKAGES', 'AD_TYPE_DESCRIPTION',
       'AVG_PRICE_PER_MEASURE', 'AVG_PRICE_PER_PACK', 'HUMAN_CONSUMABLE_CODE',
       'DIETITIAN_PICK', 'WIC_FLAG', 'FOOD_STAMP_FLAG', 'FV_DUMMY1',
       'FV_DUMMY2', 'UNIT_OF_MEASURE_mapped', 'FNDDS_SCHNUCKS',
       'standard_portion', 'transfer_g', 'final_weight', 'portion',
       'Intervention', 'COHORT #', 'Start Date', 'End Date', 'CUSTOMER_ID',
       'days_since_start', 'week_bin', 'phase', 'period_start'],
      dtype='object')

In [36]:
data["PID"].nunique()

71

# coupon matrix #

In [37]:
coupon_df=data[data['Intervention'] == 'COUPON'].copy()

In [38]:
# Filter PID 223 rows
pid223_df = data[data['PID'] == 223]

# Add them to coupon_df
coupon_df = pd.concat([coupon_df, pid223_df], ignore_index=True)

In [39]:
coupon_df.loc[coupon_df['PID'] == 223, 'Intervention'] = 'COUPON'

In [40]:
coupon_df['COHORT #'].value_counts()

COHORT #
1     2921
6     1962
8     1831
4     1579
7     1038
10     470
9      262
12     159
2       50
Name: count, dtype: int64

FV purchase

In [41]:
# Filter for FV_dummy == 1
fv_sales = coupon_df[coupon_df['FV_DUMMY1'] == 1].copy()

# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
fv_purchase = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(FV_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
fv_purchase = fv_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'FV_sales']]
fv_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,FV_sales
0,101,-24,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,21.58
1,101,-18,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,17.25
2,101,-16,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,15.92
3,101,-10,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,20.30
4,101,0,In-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-04-24,23.27
...,...,...,...,...,...,...,...,...,...,...
350,223,32,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-04-23,9.57
351,223,34,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-07,18.56
352,223,36,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,16.96
353,223,38,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,6.71
354,223,42,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,14.91

In [42]:
coupon_df["PID"].nunique()

25

In [43]:
fv_sales["PID"].nunique()

24

In [44]:
fv_purchase["PID"].nunique()

24

In [45]:
#check NAN
# Define the groupby columns
group_cols = ['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
              'Start Date', 'End Date', 'COHORT #', 'period_start']

# Find rows with any missing values in groupby keys
missing_group_keys = fv_sales[fv_sales[group_cols].isnull().any(axis=1)]

# Check how many unique PIDs were affected
num_missing_pids = missing_group_keys['PID'].nunique()
total_missing_rows = len(missing_group_keys)

print(f"Unique PIDs lost due to NaNs in groupby keys: {num_missing_pids}")
print(f"Total rows excluded from groupby due to NaNs: {total_missing_rows}")

# Optionally view some of them
missing_group_keys[['PID'] + group_cols].head()

Unique PIDs lost due to NaNs in groupby keys: 0
Total rows excluded from groupby due to NaNs: 0

Empty DataFrame
Columns: [PID, PID, week_bin, phase, Intervention, CUSTOMER_ID, Start Date, End Date, COHORT #, period_start]
Index: []

non_FV (dietitian approved)

In [46]:
coupon_df["DIETITIAN_PICK"].value_counts()

DIETITIAN_PICK
N    5428
Y    2776
Name: count, dtype: int64

In [47]:
# Filter for FV_dummy == 1
fv_sales = coupon_df[(coupon_df['FV_DUMMY1'] != 1) & (coupon_df['DIETITIAN_PICK'] == 'Y')].copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
nfv_purchase = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(NFV_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
nfv_purchase = nfv_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'NFV_sales']]
nfv_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,NFV_sales
0,101,-24,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,1.78
1,101,-18,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,2.59
2,101,-16,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,17.25
3,101,-10,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,19.96
4,101,0,In-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-04-24,3.50
...,...,...,...,...,...,...,...,...,...,...
285,223,16,In-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-01-01,8.96
286,223,22,In-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-02-12,8.88
287,223,28,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-03-26,3.98
288,223,34,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-07,2.79
289,223,38,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,4.78

In [48]:
nfv_purchase["PID"].nunique()

23

In [49]:
fv_purchase["PID"].nunique()

24

In [50]:
# Sets of PIDs
fv_pids = set(fv_purchase['PID'])
nfv_pids = set(nfv_purchase['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - nfv_pids

# Unique to nfv_purchase
nfv_only_pids = nfv_pids - fv_pids

# Show results
print("✅ Unique PIDs in fv_purchase only:", fv_only_pids)
print("✅ Unique PIDs in nfv_purchase only:", nfv_only_pids)

✅ Unique PIDs in fv_purchase only: {119}
✅ Unique PIDs in nfv_purchase only: set()

In [51]:
merged_purchase = pd.merge(
    fv_purchase,
    nfv_purchase,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase['FV_sales'] = merged_purchase['FV_sales'].fillna(0)
merged_purchase['NFV_sales'] = merged_purchase['NFV_sales'].fillna(0)
merged_purchase

,PID,week_bin,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,Start Date_fv,End Date_fv,period_start_fv,FV_sales,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,NFV_sales
0,101,-24,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,21.58,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,1.78
1,101,-18,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,17.25,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,2.59
2,101,-16,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,15.92,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,17.25
3,101,-10,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,20.30,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,19.96
4,101,0,In-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-04-24,23.27,In-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-04-24,3.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,223,32,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-04-23,9.57,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00
375,223,34,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-07,18.56,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-07,2.79
376,223,36,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21,16.96,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00
377,223,38,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,6.71,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,4.78
378,223,42,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02,14.91,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00

In [52]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase[base_col] = merged_purchase[fv_col].combine_first(merged_purchase[nfv_col])
        # Drop the original pair
        merged_purchase.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase

,PID,week_bin,FV_sales,NFV_sales,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,101,-24,21.58,1.78,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08
1,101,-18,17.25,2.59,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20
2,101,-16,15.92,17.25,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03
3,101,-10,20.30,19.96,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14
4,101,0,23.27,3.50,In-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-04-24
...,...,...,...,...,...,...,...,...,...,...,...
374,223,32,9.57,0.00,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-04-23
375,223,34,18.56,2.79,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-07
376,223,36,16.96,0.00,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21
377,223,38,6.71,4.78,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04
378,223,42,14.91,0.00,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02

non_FV (dietitian not approved)

In [53]:
# Filter for FV_dummy == 1
fv_sales = coupon_df[(coupon_df['FV_DUMMY1'] != 1) & (coupon_df['DIETITIAN_PICK'] != 'Y')].copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
other_purchase = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(other_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
other_purchase = other_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'other_sales']]
other_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,other_sales
0,101,-24,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,85.01
1,101,-18,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,100.39
2,101,-16,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,150.03
3,101,-10,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,204.20
4,101,-4,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-03-27,22.98
...,...,...,...,...,...,...,...,...,...,...
426,223,36,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,78.31
427,223,38,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,26.52
428,223,40,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-18,7.97
429,223,42,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,11.82
430,223,44,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-16,23.33

In [54]:
other_purchase["PID"].nunique()

25

In [55]:
merged_purchase1 = pd.merge(
    merged_purchase,
    other_purchase,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase1['FV_sales'] = merged_purchase1['FV_sales'].fillna(0)
merged_purchase1['NFV_sales'] = merged_purchase1['NFV_sales'].fillna(0)
merged_purchase1['other_sales'] = merged_purchase1['other_sales'].fillna(0)

merged_purchase1

,PID,week_bin,FV_sales,NFV_sales,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,Start Date_fv,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,other_sales
0,101,-24,21.58,1.78,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,85.01
1,101,-18,17.25,2.59,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,100.39
2,101,-16,15.92,17.25,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,150.03
3,101,-10,20.30,19.96,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,204.20
4,101,-4,0.00,0.00,NaN,NaN,NaN,NaN,NaT,NaT,NaT,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27,22.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21,78.31
431,223,38,6.71,4.78,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,26.52
432,223,40,0.00,0.00,NaN,NaN,NaN,NaN,NaT,NaT,NaT,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18,7.97
433,223,42,14.91,0.00,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02,11.82
434,223,44,0.00,0.00,NaN,NaN,NaN,NaN,NaT,NaT,NaT,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16,23.33

In [56]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase1.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase1.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase1.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase1[base_col] = merged_purchase1[fv_col].combine_first(merged_purchase1[nfv_col])
        # Drop the original pair
        merged_purchase1.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase1

,PID,week_bin,FV_sales,NFV_sales,other_sales,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,101,-24,21.58,1.78,85.01,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08
1,101,-18,17.25,2.59,100.39,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20
2,101,-16,15.92,17.25,150.03,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03
3,101,-10,20.30,19.96,204.20,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14
4,101,-4,0.00,0.00,22.98,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21
431,223,38,6.71,4.78,26.52,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04
432,223,40,0.00,0.00,7.97,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18
433,223,42,14.91,0.00,11.82,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02
434,223,44,0.00,0.00,23.33,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16

In [57]:
# Sets of PIDs
fv_pids = set(merged_purchase['PID'])
other_pids = set(other_purchase['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - other_pids

# Unique to nfv_purchase
other_only_pids = other_pids - fv_pids

# Show results
print("✅ Unique PIDs in fv_purchase only:", fv_only_pids)
print("✅ Unique PIDs in other_purchase only:", other_only_pids)

✅ Unique PIDs in fv_purchase only: set()
✅ Unique PIDs in other_purchase only: {136}

FV quantity

In [58]:
# Filter for FV_dummy == 1
fv_sales = coupon_df[coupon_df['FV_DUMMY1'] == 1].copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
portion = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(portion=('portion', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
portion = portion[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'portion']]
portion

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,portion
0,101,-24,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,55.709927
1,101,-18,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,44.483241
2,101,-16,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,20.353215
3,101,-10,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,48.339864
4,101,0,In-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-04-24,42.639992
...,...,...,...,...,...,...,...,...,...,...
350,223,32,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-04-23,10.508168
351,223,34,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-07,21.971250
352,223,36,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,14.653333
353,223,38,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,5.065155
354,223,42,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,9.582120

In [59]:
portion["PID"].nunique()

24

In [60]:
# Sets of PIDs
fv_pids = set(merged_purchase1['PID'])
portion_pids = set(portion['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - portion_pids

# Unique to nfv_purchase
portion_only_pids = portion_pids - fv_pids

# Show results
print("✅ Unique PIDs in fv_purchase2 only:", fv_only_pids)
print("✅ Unique PIDs in portion_purchase only:", portion_only_pids)

✅ Unique PIDs in fv_purchase2 only: {136}
✅ Unique PIDs in portion_purchase only: set()

In [61]:
merged_purchase2 = pd.merge(
    merged_purchase1,
    portion,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase2['FV_sales'] = merged_purchase2['FV_sales'].fillna(0)
merged_purchase2['NFV_sales'] = merged_purchase2['NFV_sales'].fillna(0)
merged_purchase2['other_sales'] = merged_purchase2['other_sales'].fillna(0)
merged_purchase2['portion'] = merged_purchase2['portion'].fillna(0)
merged_purchase2

,PID,week_bin,FV_sales,NFV_sales,other_sales,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,Start Date_fv,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,portion
0,101,-24,21.58,1.78,85.01,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,55.709927
1,101,-18,17.25,2.59,100.39,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,44.483241
2,101,-16,15.92,17.25,150.03,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,20.353215
3,101,-10,20.30,19.96,204.20,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,48.339864
4,101,-4,0.00,0.00,22.98,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21,14.653333
431,223,38,6.71,4.78,26.52,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,5.065155
432,223,40,0.00,0.00,7.97,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
433,223,42,14.91,0.00,11.82,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02,9.582120
434,223,44,0.00,0.00,23.33,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000

In [62]:
fv_cols = [col for col in merged_purchase2.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase2.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase2.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase2[base_col] = merged_purchase2[fv_col].combine_first(merged_purchase2[nfv_col])
        # Drop the original pair
        merged_purchase2.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase2

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,101,-24,21.58,1.78,85.01,55.709927,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08
1,101,-18,17.25,2.59,100.39,44.483241,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20
2,101,-16,15.92,17.25,150.03,20.353215,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03
3,101,-10,20.30,19.96,204.20,48.339864,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14
4,101,-4,0.00,0.00,22.98,0.000000,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,14.653333,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21
431,223,38,6.71,4.78,26.52,5.065155,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04
432,223,40,0.00,0.00,7.97,0.000000,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18
433,223,42,14.91,0.00,11.82,9.582120,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02
434,223,44,0.00,0.00,23.33,0.000000,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16

transaction and coupon

In [63]:
coupon_transaction = pd.read_excel("weekly_coupon_and_transactions.xlsx")

In [64]:
coupon_transaction

     PID  week_bin  total_coupon_used  unique_transaction_count
0    101         0             -12.91                         1
1    101         2               0.00                         2
2    101        12               0.00                         1
3    101        14               0.00                         1
4    102         0               0.00                         1
..   ...       ...                ...                       ...
137  137        10             -20.00                         1
138  139         0               0.00                         1
139  139         2               0.00                         3
140  139         4              -2.51                         3
141  139         6               0.00                         2

[142 rows x 4 columns]

In [65]:
coupon_transaction["PID"].nunique()

20

In [66]:
fv_sales = coupon_df.copy()

In [67]:
fv_sales = coupon_df.copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and count unique transactions
transaction = fv_sales.groupby(
    ['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
     'Start Date', 'End Date', 'COHORT #', 'period_start'],
    dropna=False
).agg(transaction=('TRANSACTION_HEADER_KEY', 'nunique')).reset_index()

# Reorder columns (optional)
transaction = transaction[[
    'PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
    'COHORT #', 'Start Date', 'End Date', 'period_start', 'transaction'
]]

transaction

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,transaction
0,101,-24,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,2
1,101,-18,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,1
2,101,-16,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,1
3,101,-10,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,1
4,101,-4,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-03-27,1
...,...,...,...,...,...,...,...,...,...,...
430,223,36,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,2
431,223,38,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,1
432,223,40,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-18,1
433,223,42,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,1
434,223,44,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-16,1

In [68]:
# Sets of PIDs
fv_pids = set(transaction['PID'])
coupon_pids = set(coupon_transaction['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - coupon_pids

# Unique to nfv_purchase
coupon_only_pids = coupon_pids - fv_pids

# Show results
print("✅ Unique PIDs in fv_purchase3 only:", fv_only_pids)
print("✅ Unique PIDs in coupon_purchase only:", coupon_only_pids)

✅ Unique PIDs in fv_purchase3 only: {138, 107, 140, 119, 223}
✅ Unique PIDs in coupon_purchase only: set()

In [69]:
merged_purchase3 = pd.merge(
    merged_purchase2,
    transaction,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase3['FV_sales'] = merged_purchase3['FV_sales'].fillna(0)
merged_purchase3['NFV_sales'] = merged_purchase3['NFV_sales'].fillna(0)
merged_purchase3['other_sales'] = merged_purchase3['other_sales'].fillna(0)
merged_purchase3['portion'] = merged_purchase3['portion'].fillna(0)
merged_purchase3['transaction'] = merged_purchase3['transaction'].fillna(0)
merged_purchase3

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,...,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,transaction
0,101,-24,21.58,1.78,85.01,55.709927,Pre-Trial,COUPON,311187789.0,1.0,...,2024-10-09,2023-11-08,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,2
1,101,-18,17.25,2.59,100.39,44.483241,Pre-Trial,COUPON,311187789.0,1.0,...,2024-10-09,2023-12-20,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,1
2,101,-16,15.92,17.25,150.03,20.353215,Pre-Trial,COUPON,311187789.0,1.0,...,2024-10-09,2024-01-03,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,1
3,101,-10,20.30,19.96,204.20,48.339864,Pre-Trial,COUPON,311187789.0,1.0,...,2024-10-09,2024-02-14,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,1
4,101,-4,0.00,0.00,22.98,0.000000,Pre-Trial,COUPON,311187789.0,1.0,...,2024-10-09,2024-03-27,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-03-27,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,14.653333,Post-Trial,COUPON,292422493.0,6.0,...,2025-02-26,2025-05-21,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,2
431,223,38,6.71,4.78,26.52,5.065155,Post-Trial,COUPON,292422493.0,6.0,...,2025-02-26,2025-06-04,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,1
432,223,40,0.00,0.00,7.97,0.000000,Post-Trial,COUPON,292422493.0,6.0,...,2025-02-26,2025-06-18,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-18,1
433,223,42,14.91,0.00,11.82,9.582120,Post-Trial,COUPON,292422493.0,6.0,...,2025-02-26,2025-07-02,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,1
434,223,44,0.00,0.00,23.33,0.000000,Post-Trial,COUPON,292422493.0,6.0,...,2025-02-26,2025-07-16,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-16,1

In [70]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase3.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase3.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase3.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase3[base_col] = merged_purchase3[fv_col].combine_first(merged_purchase3[nfv_col])
        # Drop the original pair
        merged_purchase3.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase3

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,101,-24,21.58,1.78,85.01,55.709927,2,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08
1,101,-18,17.25,2.59,100.39,44.483241,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20
2,101,-16,15.92,17.25,150.03,20.353215,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03
3,101,-10,20.30,19.96,204.20,48.339864,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14
4,101,-4,0.00,0.00,22.98,0.000000,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,14.653333,2,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21
431,223,38,6.71,4.78,26.52,5.065155,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04
432,223,40,0.00,0.00,7.97,0.000000,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18
433,223,42,14.91,0.00,11.82,9.582120,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02
434,223,44,0.00,0.00,23.33,0.000000,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16

In [71]:
# Step 2: Merge to fv_purchase on PID
coupon_by_pid = coupon_transaction.groupby(['PID', 'week_bin'], as_index=False)['total_coupon_used'].sum()

fv_purchase5 = pd.merge(merged_purchase3, coupon_by_pid, on=['PID', 'week_bin'], how='left')

# Fill missing values with 0
fv_purchase5[['portion', 'other_sales', 'FV_sales', 'NFV_sales', 'transaction', 'total_coupon_used']] = \
    fv_purchase5[['portion', 'other_sales', 'FV_sales', 'NFV_sales', 'transaction', 'total_coupon_used']].fillna(0)

fv_purchase5

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,total_coupon_used
0,101,-24,21.58,1.78,85.01,55.709927,2,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08,0.0
1,101,-18,17.25,2.59,100.39,44.483241,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20,0.0
2,101,-16,15.92,17.25,150.03,20.353215,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03,0.0
3,101,-10,20.30,19.96,204.20,48.339864,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14,0.0
4,101,-4,0.00,0.00,22.98,0.000000,1,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,14.653333,2,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21,0.0
431,223,38,6.71,4.78,26.52,5.065155,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04,0.0
432,223,40,0.00,0.00,7.97,0.000000,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18,0.0
433,223,42,14.91,0.00,11.82,9.582120,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02,0.0
434,223,44,0.00,0.00,23.33,0.000000,1,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16,0.0

total purchase

In [72]:
# Filter for FV_dummy == 1
sales = coupon_df.copy()

# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
total_purchase = sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(total_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
total_purchase = total_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'total_sales']]
total_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,total_sales
0,101,-24,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,108.37
1,101,-18,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,120.23
2,101,-16,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,183.20
3,101,-10,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,244.46
4,101,-4,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-03-27,22.98
...,...,...,...,...,...,...,...,...,...,...
430,223,36,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,95.27
431,223,38,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,38.01
432,223,40,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-18,7.97
433,223,42,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,26.73
434,223,44,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-16,23.33

In [73]:
merged_purchase4 = pd.merge(
    fv_purchase5,
    total_purchase,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase4['FV_sales'] = merged_purchase4['FV_sales'].fillna(0)
merged_purchase4['NFV_sales'] = merged_purchase4['NFV_sales'].fillna(0)
merged_purchase4['other_sales'] = merged_purchase4['other_sales'].fillna(0)
merged_purchase4['portion'] = merged_purchase4['portion'].fillna(0)
merged_purchase4['transaction'] = merged_purchase4['transaction'].fillna(0)
merged_purchase4['total_sales'] = merged_purchase4['total_sales'].fillna(0)
merged_purchase4

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,phase_fv,Intervention_fv,CUSTOMER_ID_fv,...,period_start_fv,total_coupon_used,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,total_sales
0,101,-24,21.58,1.78,85.01,55.709927,2,Pre-Trial,COUPON,311187789.0,...,2023-11-08,0.0,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-11-08,108.37
1,101,-18,17.25,2.59,100.39,44.483241,1,Pre-Trial,COUPON,311187789.0,...,2023-12-20,0.0,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2023-12-20,120.23
2,101,-16,15.92,17.25,150.03,20.353215,1,Pre-Trial,COUPON,311187789.0,...,2024-01-03,0.0,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-01-03,183.20
3,101,-10,20.30,19.96,204.20,48.339864,1,Pre-Trial,COUPON,311187789.0,...,2024-02-14,0.0,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-02-14,244.46
4,101,-4,0.00,0.00,22.98,0.000000,1,Pre-Trial,COUPON,311187789.0,...,2024-03-27,0.0,Pre-Trial,COUPON,311187789.0,1,2024-04-24,2024-10-09,2024-03-27,22.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,14.653333,2,Post-Trial,COUPON,292422493.0,...,2025-05-21,0.0,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-05-21,95.27
431,223,38,6.71,4.78,26.52,5.065155,1,Post-Trial,COUPON,292422493.0,...,2025-06-04,0.0,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-04,38.01
432,223,40,0.00,0.00,7.97,0.000000,1,Post-Trial,COUPON,292422493.0,...,2025-06-18,0.0,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-06-18,7.97
433,223,42,14.91,0.00,11.82,9.582120,1,Post-Trial,COUPON,292422493.0,...,2025-07-02,0.0,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-02,26.73
434,223,44,0.00,0.00,23.33,0.000000,1,Post-Trial,COUPON,292422493.0,...,2025-07-16,0.0,Post-Trial,COUPON,292422493.0,6,2024-09-11,2025-02-26,2025-07-16,23.33

In [74]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase4.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase4.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase4.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase4[base_col] = merged_purchase4[fv_col].combine_first(merged_purchase4[nfv_col])
        # Drop the original pair
        merged_purchase4.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase4

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,total_coupon_used,total_sales,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,101,-24,21.58,1.78,85.01,55.709927,2,0.0,108.37,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-11-08
1,101,-18,17.25,2.59,100.39,44.483241,1,0.0,120.23,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2023-12-20
2,101,-16,15.92,17.25,150.03,20.353215,1,0.0,183.20,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-01-03
3,101,-10,20.30,19.96,204.20,48.339864,1,0.0,244.46,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-02-14
4,101,-4,0.00,0.00,22.98,0.000000,1,0.0,22.98,Pre-Trial,COUPON,311187789.0,1.0,2024-04-24,2024-10-09,2024-03-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,223,36,16.96,0.00,78.31,14.653333,2,0.0,95.27,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-05-21
431,223,38,6.71,4.78,26.52,5.065155,1,0.0,38.01,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-04
432,223,40,0.00,0.00,7.97,0.000000,1,0.0,7.97,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-06-18
433,223,42,14.91,0.00,11.82,9.582120,1,0.0,26.73,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-02
434,223,44,0.00,0.00,23.33,0.000000,1,0.0,23.33,Post-Trial,COUPON,292422493.0,6.0,2024-09-11,2025-02-26,2025-07-16

In [75]:
merged_purchase4.columns

Index(['PID', 'week_bin', 'FV_sales', 'NFV_sales', 'other_sales', 'portion',
       'transaction', 'total_coupon_used', 'total_sales', 'phase',
       'Intervention', 'CUSTOMER_ID', 'COHORT #', 'Start Date', 'End Date',
       'period_start'],
      dtype='object')

In [76]:
merged_purchase4['FV_out_of_pocket']=merged_purchase4['FV_sales']-merged_purchase4['total_coupon_used']

In [77]:
merged_purchase4['DP_out_of_pocket ']=merged_purchase4['FV_out_of_pocket']+merged_purchase4['NFV_sales']

In [78]:
merged_purchase4.to_excel("coupon_matrix.xlsx", index=False)