In [1]:
import pandas as pd
data = pd.read_excel("data.xlsx")

In [2]:
control_df=data[data['Intervention'] == 'DELIVERY'].copy()

In [3]:
control_df['COHORT #'].value_counts()

COHORT #
7     3897
6     1983
1     1833
8     1670
9     1125
3      955
2      783
10     452
4      165
14     158
Name: count, dtype: int64

FV purchase

In [4]:
# Filter for FV_dummy == 1
fv_sales = control_df[control_df['FV_DUMMY1'] == 1].copy()

# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
fv_purchase = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(FV_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
fv_purchase = fv_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'FV_sales']]
fv_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,FV_sales
0,135,8,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,18.01
1,135,10,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,8.38
2,135,30,Post-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-07-16,9.98
3,202,-26,Pre-Trial,DELIVERY,159733124,1,2024-04-24,2024-10-09,2023-10-25,19.04
4,202,-24,Pre-Trial,DELIVERY,159733124,1,2024-04-24,2024-10-09,2023-11-08,13.96
...,...,...,...,...,...,...,...,...,...,...
325,241,12,In-Trial,DELIVERY,117646594,14,2025-05-07,2025-10-22,2025-07-30,3.00
326,243,-8,Pre-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-03-12,12.90
327,243,-4,Pre-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-04-09,1.90
328,243,6,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,3.46
329,243,8,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,4.18

In [5]:
control_df["PID"].nunique()

29

In [6]:
fv_sales["PID"].nunique()

28

In [7]:
fv_purchase["PID"].nunique()

28

non_FV (dietitian approved)

In [8]:
control_df["DIETITIAN_PICK"].value_counts()

DIETITIAN_PICK
N    7691
Y    2334
Name: count, dtype: int64

In [9]:
# Filter for FV_dummy == 1
fv_sales = control_df[(control_df['FV_DUMMY1'] != 1) & (control_df['DIETITIAN_PICK'] == 'Y')].copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
nfv_purchase = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(NFV_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
nfv_purchase = nfv_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'NFV_sales']]
nfv_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,NFV_sales
0,135,8,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,5.99
1,135,10,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,6.84
2,135,30,Post-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-07-16,11.39
3,202,-26,Pre-Trial,DELIVERY,159733124,1,2024-04-24,2024-10-09,2023-10-25,12.56
4,202,-24,Pre-Trial,DELIVERY,159733124,1,2024-04-24,2024-10-09,2023-11-08,11.41
...,...,...,...,...,...,...,...,...,...,...
315,243,2,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-05-21,6.14
316,243,4,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-04,6.14
317,243,8,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,2.09
318,243,10,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-16,6.14
319,243,12,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-30,2.51

In [10]:
# Sets of PIDs
fv_pids = set(fv_purchase['PID'])
nfv_pids = set(nfv_purchase['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - nfv_pids

# Unique to nfv_purchase
nfv_only_pids = nfv_pids - fv_pids

# Show results
print("âœ… Unique PIDs in fv_purchase only:", fv_only_pids)
print("âœ… Unique PIDs in nfv_purchase only:", nfv_only_pids)

âœ… Unique PIDs in fv_purchase only: {208, 214}
âœ… Unique PIDs in nfv_purchase only: {222}

In [11]:
merged_purchase = pd.merge(
    fv_purchase,
    nfv_purchase,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase['FV_sales'] = merged_purchase['FV_sales'].fillna(0)
merged_purchase['NFV_sales'] = merged_purchase['NFV_sales'].fillna(0)
merged_purchase

,PID,week_bin,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,Start Date_fv,End Date_fv,period_start_fv,FV_sales,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,NFV_sales
0,135,8,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12,18.01,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12,5.99
1,135,10,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26,8.38,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26,6.84
2,135,30,Post-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-07-16,9.98,Post-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-07-16,11.39
3,202,-26,Pre-Trial,DELIVERY,159733124.0,1.0,2024-04-24,2024-10-09,2023-10-25,19.04,Pre-Trial,DELIVERY,159733124.0,1.0,2024-04-24,2024-10-09,2023-10-25,12.56
4,202,-24,Pre-Trial,DELIVERY,159733124.0,1.0,2024-04-24,2024-10-09,2023-11-08,13.96,Pre-Trial,DELIVERY,159733124.0,1.0,2024-04-24,2024-10-09,2023-11-08,11.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,243,4,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04,6.14
396,243,6,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18,3.46,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00
397,243,8,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02,4.18,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02,2.09
398,243,10,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16,6.14
399,243,12,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.00,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30,2.51

In [12]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase[base_col] = merged_purchase[fv_col].combine_first(merged_purchase[nfv_col])
        # Drop the original pair
        merged_purchase.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase

,PID,week_bin,FV_sales,NFV_sales,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,135,8,18.01,5.99,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12
1,135,10,8.38,6.84,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26
2,135,30,9.98,11.39,Post-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-07-16
3,202,-26,19.04,12.56,Pre-Trial,DELIVERY,159733124.0,1.0,2024-04-24,2024-10-09,2023-10-25
4,202,-24,13.96,11.41,Pre-Trial,DELIVERY,159733124.0,1.0,2024-04-24,2024-10-09,2023-11-08
...,...,...,...,...,...,...,...,...,...,...,...
395,243,4,0.00,6.14,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04
396,243,6,3.46,0.00,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18
397,243,8,4.18,2.09,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02
398,243,10,0.00,6.14,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16
399,243,12,0.00,2.51,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30

In [13]:
merged_purchase['PID'].nunique()

29

non_FV (dietitian not approved)

In [14]:
# Filter for FV_dummy == 1
fv_sales = control_df[(control_df['FV_DUMMY1'] != 1) & (control_df['DIETITIAN_PICK'] != 'Y')].copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
other_purchase = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(other_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
other_purchase = other_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'other_sales']]
other_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,other_sales
0,135,8,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,59.93
1,135,10,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,28.03
2,135,12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-12,11.23
3,135,14,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-26,6.99
4,135,22,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-05-21,43.79
...,...,...,...,...,...,...,...,...,...,...
486,243,4,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-04,30.69
487,243,6,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,26.92
488,243,8,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,47.76
489,243,10,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-16,51.78
490,243,12,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-30,39.74

In [15]:
# Sets of PIDs
fv_pids = set(merged_purchase['PID'])
other_pids = set(other_purchase['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - other_pids

# Unique to nfv_purchase
other_only_pids = other_pids - fv_pids

# Show results
print("âœ… Unique PIDs in fv_purchase only:", fv_only_pids)
print("âœ… Unique PIDs in other_purchase only:", other_only_pids)

âœ… Unique PIDs in fv_purchase only: set()
âœ… Unique PIDs in other_purchase only: set()

In [16]:
merged_purchase1 = pd.merge(
    merged_purchase,
    other_purchase,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase1['FV_sales'] = merged_purchase1['FV_sales'].fillna(0)
merged_purchase1['NFV_sales'] = merged_purchase1['NFV_sales'].fillna(0)
merged_purchase1['other_sales'] = merged_purchase1['other_sales'].fillna(0)

merged_purchase1

,PID,week_bin,FV_sales,NFV_sales,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,Start Date_fv,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,other_sales
0,135,8,18.01,5.99,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12,59.93
1,135,10,8.38,6.84,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26,28.03
2,135,12,0.00,0.00,NaN,NaN,NaN,NaN,NaT,NaT,NaT,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-12,11.23
3,135,14,0.00,0.00,NaN,NaN,NaN,NaN,NaT,NaT,NaT,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-26,6.99
4,135,22,0.00,0.00,NaN,NaN,NaN,NaN,NaT,NaT,NaT,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-05-21,43.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04,30.69
491,243,6,3.46,0.00,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18,26.92
492,243,8,4.18,2.09,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02,47.76
493,243,10,0.00,6.14,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16,51.78
494,243,12,0.00,2.51,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30,39.74

In [17]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase1.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase1.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase1.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase1[base_col] = merged_purchase1[fv_col].combine_first(merged_purchase1[nfv_col])
        # Drop the original pair
        merged_purchase1.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase1

,PID,week_bin,FV_sales,NFV_sales,other_sales,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,135,8,18.01,5.99,59.93,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12
1,135,10,8.38,6.84,28.03,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26
2,135,12,0.00,0.00,11.23,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-12
3,135,14,0.00,0.00,6.99,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-26
4,135,22,0.00,0.00,43.79,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-05-21
...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04
491,243,6,3.46,0.00,26.92,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18
492,243,8,4.18,2.09,47.76,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02
493,243,10,0.00,6.14,51.78,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16
494,243,12,0.00,2.51,39.74,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30

FV quantity

In [18]:
# Filter for FV_dummy == 1
fv_sales = control_df[control_df['FV_DUMMY1'] == 1].copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
portion = fv_sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(portion=('portion', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
portion = portion[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'portion']]
portion

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,portion
0,135,8,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,51.249083
1,135,10,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,15.446667
2,135,30,Post-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-07-16,46.168333
3,202,-26,Pre-Trial,DELIVERY,159733124,1,2024-04-24,2024-10-09,2023-10-25,16.850368
4,202,-24,Pre-Trial,DELIVERY,159733124,1,2024-04-24,2024-10-09,2023-11-08,34.828002
...,...,...,...,...,...,...,...,...,...,...
325,241,12,In-Trial,DELIVERY,117646594,14,2025-05-07,2025-10-22,2025-07-30,1.299375
326,243,-8,Pre-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-03-12,34.000507
327,243,-4,Pre-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-04-09,7.257440
328,243,6,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,14.411250
329,243,8,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,21.153601

In [19]:
# Sets of PIDs
fv_pids = set(merged_purchase1['PID'])
portion_pids = set(portion['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - portion_pids

# Unique to nfv_purchase
portion_only_pids = portion_pids - fv_pids

# Show results
print("âœ… Unique PIDs in fv_purchase only:", fv_only_pids)
print("âœ… Unique PIDs in portion_purchase only:", portion_only_pids)

âœ… Unique PIDs in fv_purchase only: {222}
âœ… Unique PIDs in portion_purchase only: set()

In [20]:
merged_purchase2 = pd.merge(
    merged_purchase1,
    portion,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase2['FV_sales'] = merged_purchase2['FV_sales'].fillna(0)
merged_purchase2['NFV_sales'] = merged_purchase2['NFV_sales'].fillna(0)
merged_purchase2['other_sales'] = merged_purchase2['other_sales'].fillna(0)
merged_purchase2['portion'] = merged_purchase2['portion'].fillna(0)
merged_purchase2

,PID,week_bin,FV_sales,NFV_sales,other_sales,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,Start Date_fv,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,portion
0,135,8,18.01,5.99,59.93,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12,51.249083
1,135,10,8.38,6.84,28.03,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26,15.446667
2,135,12,0.00,0.00,11.23,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-12,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
3,135,14,0.00,0.00,6.99,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-26,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
4,135,22,0.00,0.00,43.79,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-05-21,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
491,243,6,3.46,0.00,26.92,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18,14.411250
492,243,8,4.18,2.09,47.76,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02,21.153601
493,243,10,0.00,6.14,51.78,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000
494,243,12,0.00,2.51,39.74,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30,NaN,NaN,NaN,NaN,NaT,NaT,NaT,0.000000

In [21]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase2.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase2.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase2.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase2[base_col] = merged_purchase2[fv_col].combine_first(merged_purchase2[nfv_col])
        # Drop the original pair
        merged_purchase2.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase2

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,135,8,18.01,5.99,59.93,51.249083,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12
1,135,10,8.38,6.84,28.03,15.446667,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26
2,135,12,0.00,0.00,11.23,0.000000,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-12
3,135,14,0.00,0.00,6.99,0.000000,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-26
4,135,22,0.00,0.00,43.79,0.000000,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-05-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,0.000000,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04
491,243,6,3.46,0.00,26.92,14.411250,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18
492,243,8,4.18,2.09,47.76,21.153601,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02
493,243,10,0.00,6.14,51.78,0.000000,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16
494,243,12,0.00,2.51,39.74,0.000000,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30

transaction

In [22]:
fv_sales = control_df.copy()


# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and count unique transactions
transaction = fv_sales.groupby(
    ['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
     'Start Date', 'End Date', 'COHORT #', 'period_start'],
    dropna=False
).agg(transaction=('TRANSACTION_HEADER_KEY', 'nunique')).reset_index()

# Reorder columns (optional)
transaction = transaction[[
    'PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
    'COHORT #', 'Start Date', 'End Date', 'period_start', 'transaction'
]]

transaction

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,transaction
0,135,8,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,2
1,135,10,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,1
2,135,12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-12,1
3,135,14,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-26,1
4,135,22,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-05-21,1
...,...,...,...,...,...,...,...,...,...,...
490,243,4,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-04,3
491,243,6,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,2
492,243,8,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,4
493,243,10,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-16,5
494,243,12,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-30,4

In [23]:
# Sets of PIDs
fv_pids = set(merged_purchase2['PID'])
portion_pids = set(transaction['PID'])

# Unique to fv_purchase
fv_only_pids = fv_pids - portion_pids

# Unique to nfv_purchase
portion_only_pids = portion_pids - fv_pids

# Show results
print("âœ… Unique PIDs in fv_purchase only:", fv_only_pids)
print("âœ… Unique PIDs in portion_purchase only:", portion_only_pids)

âœ… Unique PIDs in fv_purchase only: set()
âœ… Unique PIDs in portion_purchase only: set()

In [24]:
merged_purchase3 = pd.merge(
    merged_purchase2,
    transaction,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase3['FV_sales'] = merged_purchase3['FV_sales'].fillna(0)
merged_purchase3['NFV_sales'] = merged_purchase3['NFV_sales'].fillna(0)
merged_purchase3['other_sales'] = merged_purchase3['other_sales'].fillna(0)
merged_purchase3['portion'] = merged_purchase3['portion'].fillna(0)
merged_purchase3['transaction'] = merged_purchase3['transaction'].fillna(0)
merged_purchase3

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,phase_fv,Intervention_fv,CUSTOMER_ID_fv,COHORT #_fv,...,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,transaction
0,135,8,18.01,5.99,59.93,51.249083,In-Trial,DELIVERY,756859993.0,9.0,...,2025-06-04,2025-02-12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,2
1,135,10,8.38,6.84,28.03,15.446667,In-Trial,DELIVERY,756859993.0,9.0,...,2025-06-04,2025-02-26,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,1
2,135,12,0.00,0.00,11.23,0.000000,In-Trial,DELIVERY,756859993.0,9.0,...,2025-06-04,2025-03-12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-12,1
3,135,14,0.00,0.00,6.99,0.000000,In-Trial,DELIVERY,756859993.0,9.0,...,2025-06-04,2025-03-26,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-26,1
4,135,22,0.00,0.00,43.79,0.000000,In-Trial,DELIVERY,756859993.0,9.0,...,2025-06-04,2025-05-21,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-05-21,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,0.000000,In-Trial,DELIVERY,929120314.0,14.0,...,2025-10-22,2025-06-04,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-04,3
491,243,6,3.46,0.00,26.92,14.411250,In-Trial,DELIVERY,929120314.0,14.0,...,2025-10-22,2025-06-18,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,2
492,243,8,4.18,2.09,47.76,21.153601,In-Trial,DELIVERY,929120314.0,14.0,...,2025-10-22,2025-07-02,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,4
493,243,10,0.00,6.14,51.78,0.000000,In-Trial,DELIVERY,929120314.0,14.0,...,2025-10-22,2025-07-16,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-16,5
494,243,12,0.00,2.51,39.74,0.000000,In-Trial,DELIVERY,929120314.0,14.0,...,2025-10-22,2025-07-30,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-30,4

In [25]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase3.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase3.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase3.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase3[base_col] = merged_purchase3[fv_col].combine_first(merged_purchase3[nfv_col])
        # Drop the original pair
        merged_purchase3.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase3

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,135,8,18.01,5.99,59.93,51.249083,2,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12
1,135,10,8.38,6.84,28.03,15.446667,1,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26
2,135,12,0.00,0.00,11.23,0.000000,1,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-12
3,135,14,0.00,0.00,6.99,0.000000,1,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-26
4,135,22,0.00,0.00,43.79,0.000000,1,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-05-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,0.000000,3,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04
491,243,6,3.46,0.00,26.92,14.411250,2,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18
492,243,8,4.18,2.09,47.76,21.153601,4,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02
493,243,10,0.00,6.14,51.78,0.000000,5,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16
494,243,12,0.00,2.51,39.74,0.000000,4,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30

total purchase

In [26]:
# Filter for FV_dummy == 1
sales = control_df.copy()

# Optional: ensure 'days_since_start' and 'week_bin' are already computed
# fv_sales['days_since_start'] = (fv_sales['FULL_DATE'] - fv_sales['Start Date']).dt.days
# fv_sales['week_bin'] = (fv_sales['days_since_start'] // 14) * 2

# Group and sum SALES
total_purchase = sales.groupby(['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID', 
                            'Start Date', 'End Date', 'COHORT #', 'period_start'],dropna=False) \
                  .agg(total_sales=('SALES', 'sum')) \
                  .reset_index()

# Reorder columns (optional)
total_purchase = total_purchase[['PID', 'week_bin', 'phase', 'Intervention', 'CUSTOMER_ID',
                   'COHORT #', 'Start Date', 'End Date', 'period_start', 'total_sales']]
total_purchase

,PID,week_bin,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start,total_sales
0,135,8,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,83.93
1,135,10,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,43.25
2,135,12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-12,11.23
3,135,14,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-26,6.99
4,135,22,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-05-21,43.79
...,...,...,...,...,...,...,...,...,...,...
490,243,4,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-04,36.83
491,243,6,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,30.38
492,243,8,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,54.03
493,243,10,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-16,57.92
494,243,12,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-30,42.25

In [27]:
merged_purchase4 = pd.merge(
    merged_purchase3,
    total_purchase,
    on=['PID', 'week_bin'],
    how='outer',
    suffixes=('_fv', '_nfv')
)

# Fill missing FV/NFV sales with 0
merged_purchase4['FV_sales'] = merged_purchase4['FV_sales'].fillna(0)
merged_purchase4['NFV_sales'] = merged_purchase4['NFV_sales'].fillna(0)
merged_purchase4['other_sales'] = merged_purchase4['other_sales'].fillna(0)
merged_purchase4['portion'] = merged_purchase4['portion'].fillna(0)
merged_purchase4['transaction'] = merged_purchase4['transaction'].fillna(0)
merged_purchase4['total_sales'] = merged_purchase4['total_sales'].fillna(0)
merged_purchase4

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,phase_fv,Intervention_fv,CUSTOMER_ID_fv,...,End Date_fv,period_start_fv,phase_nfv,Intervention_nfv,CUSTOMER_ID_nfv,COHORT #_nfv,Start Date_nfv,End Date_nfv,period_start_nfv,total_sales
0,135,8,18.01,5.99,59.93,51.249083,2,In-Trial,DELIVERY,756859993.0,...,2025-06-04,2025-02-12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-12,83.93
1,135,10,8.38,6.84,28.03,15.446667,1,In-Trial,DELIVERY,756859993.0,...,2025-06-04,2025-02-26,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-02-26,43.25
2,135,12,0.00,0.00,11.23,0.000000,1,In-Trial,DELIVERY,756859993.0,...,2025-06-04,2025-03-12,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-12,11.23
3,135,14,0.00,0.00,6.99,0.000000,1,In-Trial,DELIVERY,756859993.0,...,2025-06-04,2025-03-26,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-03-26,6.99
4,135,22,0.00,0.00,43.79,0.000000,1,In-Trial,DELIVERY,756859993.0,...,2025-06-04,2025-05-21,In-Trial,DELIVERY,756859993,9,2024-12-18,2025-06-04,2025-05-21,43.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,0.000000,3,In-Trial,DELIVERY,929120314.0,...,2025-10-22,2025-06-04,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-04,36.83
491,243,6,3.46,0.00,26.92,14.411250,2,In-Trial,DELIVERY,929120314.0,...,2025-10-22,2025-06-18,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-06-18,30.38
492,243,8,4.18,2.09,47.76,21.153601,4,In-Trial,DELIVERY,929120314.0,...,2025-10-22,2025-07-02,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-02,54.03
493,243,10,0.00,6.14,51.78,0.000000,5,In-Trial,DELIVERY,929120314.0,...,2025-10-22,2025-07-16,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-16,57.92
494,243,12,0.00,2.51,39.74,0.000000,4,In-Trial,DELIVERY,929120314.0,...,2025-10-22,2025-07-30,In-Trial,DELIVERY,929120314,14,2025-05-07,2025-10-22,2025-07-30,42.25

In [28]:
# Identify all matching *_fv and *_nfv column pairs
fv_cols = [col for col in merged_purchase4.columns if col.endswith('_fv')]
nfv_cols = [col for col in merged_purchase4.columns if col.endswith('_nfv')]

# Combine matching pairs
for fv_col in fv_cols:
    base_col = fv_col[:-3]  # remove '_fv'
    nfv_col = base_col + '_nfv'
    if nfv_col in merged_purchase4.columns:
        # Combine values: take fv_col unless it's NaN, then take nfv_col
        merged_purchase4[base_col] = merged_purchase4[fv_col].combine_first(merged_purchase4[nfv_col])
        # Drop the original pair
        merged_purchase4.drop(columns=[fv_col, nfv_col], inplace=True)
merged_purchase4

,PID,week_bin,FV_sales,NFV_sales,other_sales,portion,transaction,total_sales,phase,Intervention,CUSTOMER_ID,COHORT #,Start Date,End Date,period_start
0,135,8,18.01,5.99,59.93,51.249083,2,83.93,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-12
1,135,10,8.38,6.84,28.03,15.446667,1,43.25,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-02-26
2,135,12,0.00,0.00,11.23,0.000000,1,11.23,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-12
3,135,14,0.00,0.00,6.99,0.000000,1,6.99,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-03-26
4,135,22,0.00,0.00,43.79,0.000000,1,43.79,In-Trial,DELIVERY,756859993.0,9.0,2024-12-18,2025-06-04,2025-05-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,243,4,0.00,6.14,30.69,0.000000,3,36.83,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-04
491,243,6,3.46,0.00,26.92,14.411250,2,30.38,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-06-18
492,243,8,4.18,2.09,47.76,21.153601,4,54.03,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-02
493,243,10,0.00,6.14,51.78,0.000000,5,57.92,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-16
494,243,12,0.00,2.51,39.74,0.000000,4,42.25,In-Trial,DELIVERY,929120314.0,14.0,2025-05-07,2025-10-22,2025-07-30

In [29]:
merged_purchase4.columns

Index(['PID', 'week_bin', 'FV_sales', 'NFV_sales', 'other_sales', 'portion',
       'transaction', 'total_sales', 'phase', 'Intervention', 'CUSTOMER_ID',
       'COHORT #', 'Start Date', 'End Date', 'period_start'],
      dtype='object')

In [30]:
merged_purchase4['FV_out_of_pocket']=merged_purchase4['FV_sales']

In [31]:
merged_purchase4['DP_out_of_pocket ']=merged_purchase4['FV_sales']+merged_purchase4['NFV_sales']

In [32]:
merged_purchase4.to_excel("delivery_matrix.xlsx", index=False)

In [33]:
merged_purchase4["PID"].unique()

array([135, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 214, 215,
       216, 218, 219, 222, 223, 224, 227, 229, 230, 233, 234, 237, 238,
       239, 241, 243])